class GrafanaGitHubBackup:
    def __init__(self, host, GRAFANA_API_TOKEN, GITHUB_API_TOKEN, GITHUB_REPOSITORY_NAME, GITHUB_REPOSITORY_OWNER):
        self.host = host
        self.GRAFANA_API_TOKEN = GRAFANA_API_TOKEN
        self.GITHUB_API_TOKEN = GITHUB_API_TOKEN
        self.GITHUB_REPOSITORY_NAME = GITHUB_REPOSITORY_NAME
        self.GITHUB_REPOSITORY_OWNER = GITHUB_REPOSITORY_OWNER
    